CREATE DATABASE DBMarca
go
use DBMarca
go

CREATE TABLE Patrimonio
(
	Id INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(50) NOT NULL,
	MarcaId INT NOT NULL,
	Descricao VARCHAR(50) NULL,
	NumeroTombo INT NOT NULL
)

CREATE TABLE Marca
(
	MarcaId INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(50) NOT NULL,	
)